# Generated by Django 4.0.2 on 2022-07-07 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0002_category_thread_author_thread_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='category',
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='forums.category')),
            ],
        ),
        migrations.AddField(
            model_name='thread',
            name='forum',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='forums.forum'),
            preserve_default=False,
        ),
    ]
