# Generated by Django 4.0.2 on 2022-07-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0003_remove_thread_category_forum_thread_forum'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
