# Generated by Django 4.0.2 on 2022-07-07 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_avatar'),
        ('forums', '0004_alter_category_options_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='icon',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
                ('thread', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='forums.thread')),
            ],
        ),
    ]
